// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"application/app"
	"application/internal/biz"
	"application/internal/gateway"
	"application/internal/service"
	"application/internal/service/handler"
	"application/pkg/middlewares"
	"context"
	"net/http"
)

// Injectors from wire.go:

// wireApp is the composition root for the gateway binary. It reuses the shared
// app + HTTP infrastructure and shared healthz, adds the JWT auth middleware
// (admin route guard) and the reverse-proxy dispatcher. No datasource is wired —
// the gateway holds no state, it only proxies.
func wireApp(ctx context.Context) (app.Application, error) {
	runTimeFlags := app.NewRunTimeFlags()
	kConfig, err := app.NewKoanfConfig(runTimeFlags)
	if err != nil {
		return nil, err
	}
	appConfig, err := app.NewAppConfig(ctx, kConfig)
	if err != nil {
		return nil, err
	}
	httpServerConfig, err := app.NewHTTPServerConfig(ctx, kConfig)
	if err != nil {
		return nil, err
	}
	appLoggerConfig, err := app.NewAppLoggerConfig(kConfig)
	if err != nil {
		return nil, err
	}
	collectorConfig, err := app.NewCollectorConfig(ctx, kConfig)
	if err != nil {
		return nil, err
	}
	controller := app.NewController()
	otlp, err := app.NewOTLP(ctx, collectorConfig, appConfig, controller, httpServerConfig)
	if err != nil {
		return nil, err
	}
	appLogger, err := app.NewAppLogger(ctx, appConfig, appLoggerConfig, otlp)
	if err != nil {
		return nil, err
	}
	logger := app.NewSlogLogger(appLogger)
	serveMux := http.NewServeMux()
	healthz := biz.NewHealthz(logger, controller)
	healthzHandler := handler.NewMuxHealthzHandler(healthz, logger, serveMux)
	gatewayConfig, err := gateway.NewGatewayConfig(ctx, kConfig)
	if err != nil {
		return nil, err
	}
	jwtSecret, err := middlewares.NewJWTSecret(kConfig)
	if err != nil {
		return nil, err
	}
	jwtAuth := middlewares.NewJWTAuth(jwtSecret)
	gatewayGateway, err := gateway.NewGateway(logger, serveMux, gatewayConfig, jwtAuth)
	if err != nil {
		return nil, err
	}
	v := gateway.NewServiceList(healthzHandler, gatewayGateway)
	httpHandler, err := service.NewHTTPHandler(ctx, logger, serveMux, v...)
	if err != nil {
		return nil, err
	}
	httpServer := app.NewHTTPServer(httpServerConfig, httpHandler, appLogger)
	appApp := app.NewApp(runTimeFlags, appConfig, httpServer, appLogger, controller)
	return appApp, nil
}
