// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"application/app"
	biz2 "application/internal/adminauth/biz"
	handler2 "application/internal/adminauth/handler"
	"application/internal/adminauth/repo"
	"application/internal/biz"
	"application/internal/datasource"
	"application/internal/service"
	"application/internal/service/handler"
	"application/pkg/middlewares"
	"context"
	"net/http"
)

// Injectors from wire.go:

// wireApp is the composition root for the adminauth service binary. It reuses
// the shared app + HTTP infrastructure and Postgres datasource, adds the
// shared healthz endpoints, and the adminauth domain stack.
func wireApp(ctx context.Context) (app.Application, error) {
	runTimeFlags := app.NewRunTimeFlags()
	kConfig, err := app.NewKoanfConfig(runTimeFlags)
	if err != nil {
		return nil, err
	}
	appConfig, err := app.NewAppConfig(ctx, kConfig)
	if err != nil {
		return nil, err
	}
	httpServerConfig, err := app.NewHTTPServerConfig(ctx, kConfig)
	if err != nil {
		return nil, err
	}
	appLoggerConfig, err := app.NewAppLoggerConfig(kConfig)
	if err != nil {
		return nil, err
	}
	collectorConfig, err := app.NewCollectorConfig(ctx, kConfig)
	if err != nil {
		return nil, err
	}
	controller := app.NewController()
	otlp, err := app.NewOTLP(ctx, collectorConfig, appConfig, controller, httpServerConfig)
	if err != nil {
		return nil, err
	}
	appLogger, err := app.NewAppLogger(ctx, appConfig, appLoggerConfig, otlp)
	if err != nil {
		return nil, err
	}
	logger := app.NewSlogLogger(appLogger)
	serveMux := http.NewServeMux()
	healthz := biz.NewHealthz(logger, controller)
	healthzHandler := handler.NewMuxHealthzHandler(healthz, logger, serveMux)
	postgresConfig, err := datasource.NewPostgresConfig(ctx, kConfig)
	if err != nil {
		return nil, err
	}
	postgresDB, err := datasource.NewPostgresDB(ctx, logger, controller, postgresConfig)
	if err != nil {
		return nil, err
	}
	admin := repo.NewAdmin(logger, postgresDB)
	jwtSecret, err := middlewares.NewJWTSecret(kConfig)
	if err != nil {
		return nil, err
	}
	config, err := biz2.NewConfig(kConfig)
	if err != nil {
		return nil, err
	}
	bizAuth := biz2.NewAuth(logger, admin, jwtSecret, config)
	jwtAuth := middlewares.NewJWTAuth(jwtSecret)
	handlerAuth := handler2.NewAuth(logger, serveMux, bizAuth, jwtAuth)
	bizAccounts := biz2.NewAccounts(logger, admin)
	recorder := handler2.NewAuditRecorder(logger, postgresDB)
	handlerAccounts := handler2.NewAccounts(logger, serveMux, bizAccounts, jwtAuth, recorder)
	bootstrapDone, err := handler2.RunBootstrap(ctx, logger, config, admin)
	if err != nil {
		return nil, err
	}
	v := handler2.NewServiceList(healthzHandler, handlerAuth, handlerAccounts, bootstrapDone)
	httpHandler, err := service.NewHTTPHandler(ctx, logger, serveMux, v...)
	if err != nil {
		return nil, err
	}
	httpServer := app.NewHTTPServer(httpServerConfig, httpHandler, appLogger)
	appApp := app.NewApp(runTimeFlags, appConfig, httpServer, appLogger, controller)
	return appApp, nil
}
