// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	biz "application/internal/draw/biz"
	context "context"

	entity "application/internal/draw/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUsecaseDraw is an autogenerated mock type for the UsecaseDraw type
type MockUsecaseDraw struct {
	mock.Mock
}

type MockUsecaseDraw_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecaseDraw) EXPECT() *MockUsecaseDraw_Expecter {
	return &MockUsecaseDraw_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, in
func (_m *MockUsecaseDraw) Create(ctx context.Context, in biz.CreateInput) (entity.Draw, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.Draw
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.CreateInput) (entity.Draw, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, biz.CreateInput) entity.Draw); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(entity.Draw)
	}

	if rf, ok := ret.Get(1).(func(context.Context, biz.CreateInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseDraw_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUsecaseDraw_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - in biz.CreateInput
func (_e *MockUsecaseDraw_Expecter) Create(ctx interface{}, in interface{}) *MockUsecaseDraw_Create_Call {
	return &MockUsecaseDraw_Create_Call{Call: _e.mock.On("Create", ctx, in)}
}

func (_c *MockUsecaseDraw_Create_Call) Run(run func(ctx context.Context, in biz.CreateInput)) *MockUsecaseDraw_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.CreateInput))
	})
	return _c
}

func (_c *MockUsecaseDraw_Create_Call) Return(_a0 entity.Draw, _a1 error) *MockUsecaseDraw_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseDraw_Create_Call) RunAndReturn(run func(context.Context, biz.CreateInput) (entity.Draw, error)) *MockUsecaseDraw_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockUsecaseDraw) Get(ctx context.Context, id uuid.UUID) (entity.Draw, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.Draw
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Draw, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Draw); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Draw)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseDraw_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUsecaseDraw_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsecaseDraw_Expecter) Get(ctx interface{}, id interface{}) *MockUsecaseDraw_Get_Call {
	return &MockUsecaseDraw_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockUsecaseDraw_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsecaseDraw_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseDraw_Get_Call) Return(_a0 entity.Draw, _a1 error) *MockUsecaseDraw_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseDraw_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Draw, error)) *MockUsecaseDraw_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublic provides a mock function with given fields: ctx, id
func (_m *MockUsecaseDraw) GetPublic(ctx context.Context, id uuid.UUID) (entity.Draw, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPublic")
	}

	var r0 entity.Draw
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Draw, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Draw); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Draw)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseDraw_GetPublic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublic'
type MockUsecaseDraw_GetPublic_Call struct {
	*mock.Call
}

// GetPublic is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsecaseDraw_Expecter) GetPublic(ctx interface{}, id interface{}) *MockUsecaseDraw_GetPublic_Call {
	return &MockUsecaseDraw_GetPublic_Call{Call: _e.mock.On("GetPublic", ctx, id)}
}

func (_c *MockUsecaseDraw_GetPublic_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsecaseDraw_GetPublic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseDraw_GetPublic_Call) Return(_a0 entity.Draw, _a1 error) *MockUsecaseDraw_GetPublic_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseDraw_GetPublic_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Draw, error)) *MockUsecaseDraw_GetPublic_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockUsecaseDraw) List(ctx context.Context, filter biz.ListFilter) (biz.DrawPage, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 biz.DrawPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.ListFilter) (biz.DrawPage, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, biz.ListFilter) biz.DrawPage); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(biz.DrawPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, biz.ListFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseDraw_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUsecaseDraw_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter biz.ListFilter
func (_e *MockUsecaseDraw_Expecter) List(ctx interface{}, filter interface{}) *MockUsecaseDraw_List_Call {
	return &MockUsecaseDraw_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockUsecaseDraw_List_Call) Run(run func(ctx context.Context, filter biz.ListFilter)) *MockUsecaseDraw_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.ListFilter))
	})
	return _c
}

func (_c *MockUsecaseDraw_List_Call) Return(_a0 biz.DrawPage, _a1 error) *MockUsecaseDraw_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseDraw_List_Call) RunAndReturn(run func(context.Context, biz.ListFilter) (biz.DrawPage, error)) *MockUsecaseDraw_List_Call {
	_c.Call.Return(run)
	return _c
}

// Reassign provides a mock function with given fields: ctx, id, ticketID, reason
func (_m *MockUsecaseDraw) Reassign(ctx context.Context, id uuid.UUID, ticketID uuid.UUID, reason string) (entity.Draw, error) {
	ret := _m.Called(ctx, id, ticketID, reason)

	if len(ret) == 0 {
		panic("no return value specified for Reassign")
	}

	var r0 entity.Draw
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (entity.Draw, error)); ok {
		return rf(ctx, id, ticketID, reason)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) entity.Draw); ok {
		r0 = rf(ctx, id, ticketID, reason)
	} else {
		r0 = ret.Get(0).(entity.Draw)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = rf(ctx, id, ticketID, reason)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseDraw_Reassign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reassign'
type MockUsecaseDraw_Reassign_Call struct {
	*mock.Call
}

// Reassign is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - ticketID uuid.UUID
//   - reason string
func (_e *MockUsecaseDraw_Expecter) Reassign(ctx interface{}, id interface{}, ticketID interface{}, reason interface{}) *MockUsecaseDraw_Reassign_Call {
	return &MockUsecaseDraw_Reassign_Call{Call: _e.mock.On("Reassign", ctx, id, ticketID, reason)}
}

func (_c *MockUsecaseDraw_Reassign_Call) Run(run func(ctx context.Context, id uuid.UUID, ticketID uuid.UUID, reason string)) *MockUsecaseDraw_Reassign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MockUsecaseDraw_Reassign_Call) Return(_a0 entity.Draw, _a1 error) *MockUsecaseDraw_Reassign_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseDraw_Reassign_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) (entity.Draw, error)) *MockUsecaseDraw_Reassign_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function with given fields: ctx, id
func (_m *MockUsecaseDraw) Run(ctx context.Context, id uuid.UUID) (entity.Draw, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 entity.Draw
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Draw, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Draw); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Draw)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseDraw_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockUsecaseDraw_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsecaseDraw_Expecter) Run(ctx interface{}, id interface{}) *MockUsecaseDraw_Run_Call {
	return &MockUsecaseDraw_Run_Call{Call: _e.mock.On("Run", ctx, id)}
}

func (_c *MockUsecaseDraw_Run_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsecaseDraw_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseDraw_Run_Call) Return(_a0 entity.Draw, _a1 error) *MockUsecaseDraw_Run_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseDraw_Run_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Draw, error)) *MockUsecaseDraw_Run_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePrize provides a mock function with given fields: ctx, id, prize
func (_m *MockUsecaseDraw) UpdatePrize(ctx context.Context, id uuid.UUID, prize string) (entity.Draw, error) {
	ret := _m.Called(ctx, id, prize)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePrize")
	}

	var r0 entity.Draw
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (entity.Draw, error)); ok {
		return rf(ctx, id, prize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) entity.Draw); ok {
		r0 = rf(ctx, id, prize)
	} else {
		r0 = ret.Get(0).(entity.Draw)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, id, prize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseDraw_UpdatePrize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePrize'
type MockUsecaseDraw_UpdatePrize_Call struct {
	*mock.Call
}

// UpdatePrize is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - prize string
func (_e *MockUsecaseDraw_Expecter) UpdatePrize(ctx interface{}, id interface{}, prize interface{}) *MockUsecaseDraw_UpdatePrize_Call {
	return &MockUsecaseDraw_UpdatePrize_Call{Call: _e.mock.On("UpdatePrize", ctx, id, prize)}
}

func (_c *MockUsecaseDraw_UpdatePrize_Call) Run(run func(ctx context.Context, id uuid.UUID, prize string)) *MockUsecaseDraw_UpdatePrize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockUsecaseDraw_UpdatePrize_Call) Return(_a0 entity.Draw, _a1 error) *MockUsecaseDraw_UpdatePrize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseDraw_UpdatePrize_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (entity.Draw, error)) *MockUsecaseDraw_UpdatePrize_Call {
	_c.Call.Return(run)
	return _c
}

// Void provides a mock function with given fields: ctx, id, reason
func (_m *MockUsecaseDraw) Void(ctx context.Context, id uuid.UUID, reason string) (entity.Draw, error) {
	ret := _m.Called(ctx, id, reason)

	if len(ret) == 0 {
		panic("no return value specified for Void")
	}

	var r0 entity.Draw
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (entity.Draw, error)); ok {
		return rf(ctx, id, reason)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) entity.Draw); ok {
		r0 = rf(ctx, id, reason)
	} else {
		r0 = ret.Get(0).(entity.Draw)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, id, reason)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseDraw_Void_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Void'
type MockUsecaseDraw_Void_Call struct {
	*mock.Call
}

// Void is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - reason string
func (_e *MockUsecaseDraw_Expecter) Void(ctx interface{}, id interface{}, reason interface{}) *MockUsecaseDraw_Void_Call {
	return &MockUsecaseDraw_Void_Call{Call: _e.mock.On("Void", ctx, id, reason)}
}

func (_c *MockUsecaseDraw_Void_Call) Run(run func(ctx context.Context, id uuid.UUID, reason string)) *MockUsecaseDraw_Void_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockUsecaseDraw_Void_Call) Return(_a0 entity.Draw, _a1 error) *MockUsecaseDraw_Void_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseDraw_Void_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (entity.Draw, error)) *MockUsecaseDraw_Void_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecaseDraw creates a new instance of MockUsecaseDraw. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecaseDraw(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecaseDraw {
	mock := &MockUsecaseDraw{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
