// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	biz "application/internal/draw/biz"
	entity "application/internal/draw/entity"
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, d
func (_m *MockRepository) Create(ctx context.Context, d entity.Draw) (entity.Draw, error) {
	ret := _m.Called(ctx, d)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.Draw
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Draw) (entity.Draw, error)); ok {
		return rf(ctx, d)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Draw) entity.Draw); ok {
		r0 = rf(ctx, d)
	} else {
		r0 = ret.Get(0).(entity.Draw)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Draw) error); ok {
		r1 = rf(ctx, d)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - d entity.Draw
func (_e *MockRepository_Expecter) Create(ctx interface{}, d interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, d)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, d entity.Draw)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Draw))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 entity.Draw, _a1 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, entity.Draw) (entity.Draw, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockRepository) Get(ctx context.Context, id uuid.UUID) (entity.Draw, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.Draw
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Draw, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Draw); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Draw)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) Get(ctx interface{}, id interface{}) *MockRepository_Get_Call {
	return &MockRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_Get_Call) Return(_a0 entity.Draw, _a1 error) *MockRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Draw, error)) *MockRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockRepository) List(ctx context.Context, filter biz.ListFilter) (biz.DrawPage, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 biz.DrawPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.ListFilter) (biz.DrawPage, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, biz.ListFilter) biz.DrawPage); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(biz.DrawPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, biz.ListFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter biz.ListFilter
func (_e *MockRepository_Expecter) List(ctx interface{}, filter interface{}) *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockRepository_List_Call) Run(run func(ctx context.Context, filter biz.ListFilter)) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.ListFilter))
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(_a0 biz.DrawPage, _a1 error) *MockRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func(context.Context, biz.ListFilter) (biz.DrawPage, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function with given fields: ctx, id
func (_m *MockRepository) Run(ctx context.Context, id uuid.UUID) (entity.Draw, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 entity.Draw
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Draw, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Draw); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Draw)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockRepository_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) Run(ctx interface{}, id interface{}) *MockRepository_Run_Call {
	return &MockRepository_Run_Call{Call: _e.mock.On("Run", ctx, id)}
}

func (_c *MockRepository_Run_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_Run_Call) Return(_a0 entity.Draw, _a1 error) *MockRepository_Run_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Run_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Draw, error)) *MockRepository_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
