// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	biz "application/internal/draw/biz"
	context "context"

	entity "application/internal/draw/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, d
func (_m *MockRepository) Create(ctx context.Context, d entity.Draw) (entity.Draw, error) {
	ret := _m.Called(ctx, d)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.Draw
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Draw) (entity.Draw, error)); ok {
		return rf(ctx, d)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Draw) entity.Draw); ok {
		r0 = rf(ctx, d)
	} else {
		r0 = ret.Get(0).(entity.Draw)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Draw) error); ok {
		r1 = rf(ctx, d)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - d entity.Draw
func (_e *MockRepository_Expecter) Create(ctx interface{}, d interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, d)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, d entity.Draw)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Draw))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 entity.Draw, _a1 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, entity.Draw) (entity.Draw, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockRepository) Get(ctx context.Context, id uuid.UUID) (entity.Draw, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.Draw
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Draw, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Draw); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Draw)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) Get(ctx interface{}, id interface{}) *MockRepository_Get_Call {
	return &MockRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_Get_Call) Return(_a0 entity.Draw, _a1 error) *MockRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Draw, error)) *MockRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockRepository) List(ctx context.Context, filter biz.ListFilter) (biz.DrawPage, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 biz.DrawPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.ListFilter) (biz.DrawPage, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, biz.ListFilter) biz.DrawPage); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(biz.DrawPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, biz.ListFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter biz.ListFilter
func (_e *MockRepository_Expecter) List(ctx interface{}, filter interface{}) *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockRepository_List_Call) Run(run func(ctx context.Context, filter biz.ListFilter)) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.ListFilter))
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(_a0 biz.DrawPage, _a1 error) *MockRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func(context.Context, biz.ListFilter) (biz.DrawPage, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListWinners provides a mock function with given fields: ctx, limit
func (_m *MockRepository) ListWinners(ctx context.Context, limit int) ([]entity.WinnerItem, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListWinners")
	}

	var r0 []entity.WinnerItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]entity.WinnerItem, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []entity.WinnerItem); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.WinnerItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListWinners_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWinners'
type MockRepository_ListWinners_Call struct {
	*mock.Call
}

// ListWinners is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockRepository_Expecter) ListWinners(ctx interface{}, limit interface{}) *MockRepository_ListWinners_Call {
	return &MockRepository_ListWinners_Call{Call: _e.mock.On("ListWinners", ctx, limit)}
}

func (_c *MockRepository_ListWinners_Call) Run(run func(ctx context.Context, limit int)) *MockRepository_ListWinners_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockRepository_ListWinners_Call) Return(_a0 []entity.WinnerItem, _a1 error) *MockRepository_ListWinners_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListWinners_Call) RunAndReturn(run func(context.Context, int) ([]entity.WinnerItem, error)) *MockRepository_ListWinners_Call {
	_c.Call.Return(run)
	return _c
}

// Reassign provides a mock function with given fields: ctx, id, ticketID
func (_m *MockRepository) Reassign(ctx context.Context, id uuid.UUID, ticketID uuid.UUID) (entity.Draw, error) {
	ret := _m.Called(ctx, id, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for Reassign")
	}

	var r0 entity.Draw
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (entity.Draw, error)); ok {
		return rf(ctx, id, ticketID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) entity.Draw); ok {
		r0 = rf(ctx, id, ticketID)
	} else {
		r0 = ret.Get(0).(entity.Draw)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, id, ticketID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Reassign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reassign'
type MockRepository_Reassign_Call struct {
	*mock.Call
}

// Reassign is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - ticketID uuid.UUID
func (_e *MockRepository_Expecter) Reassign(ctx interface{}, id interface{}, ticketID interface{}) *MockRepository_Reassign_Call {
	return &MockRepository_Reassign_Call{Call: _e.mock.On("Reassign", ctx, id, ticketID)}
}

func (_c *MockRepository_Reassign_Call) Run(run func(ctx context.Context, id uuid.UUID, ticketID uuid.UUID)) *MockRepository_Reassign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_Reassign_Call) Return(_a0 entity.Draw, _a1 error) *MockRepository_Reassign_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Reassign_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (entity.Draw, error)) *MockRepository_Reassign_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function with given fields: ctx, id
func (_m *MockRepository) Run(ctx context.Context, id uuid.UUID) (entity.Draw, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 entity.Draw
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Draw, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Draw); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Draw)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockRepository_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) Run(ctx interface{}, id interface{}) *MockRepository_Run_Call {
	return &MockRepository_Run_Call{Call: _e.mock.On("Run", ctx, id)}
}

func (_c *MockRepository_Run_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_Run_Call) Return(_a0 entity.Draw, _a1 error) *MockRepository_Run_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Run_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Draw, error)) *MockRepository_Run_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePrize provides a mock function with given fields: ctx, id, prize
func (_m *MockRepository) UpdatePrize(ctx context.Context, id uuid.UUID, prize string) (entity.Draw, error) {
	ret := _m.Called(ctx, id, prize)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePrize")
	}

	var r0 entity.Draw
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (entity.Draw, error)); ok {
		return rf(ctx, id, prize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) entity.Draw); ok {
		r0 = rf(ctx, id, prize)
	} else {
		r0 = ret.Get(0).(entity.Draw)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, id, prize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpdatePrize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePrize'
type MockRepository_UpdatePrize_Call struct {
	*mock.Call
}

// UpdatePrize is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - prize string
func (_e *MockRepository_Expecter) UpdatePrize(ctx interface{}, id interface{}, prize interface{}) *MockRepository_UpdatePrize_Call {
	return &MockRepository_UpdatePrize_Call{Call: _e.mock.On("UpdatePrize", ctx, id, prize)}
}

func (_c *MockRepository_UpdatePrize_Call) Run(run func(ctx context.Context, id uuid.UUID, prize string)) *MockRepository_UpdatePrize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_UpdatePrize_Call) Return(_a0 entity.Draw, _a1 error) *MockRepository_UpdatePrize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpdatePrize_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (entity.Draw, error)) *MockRepository_UpdatePrize_Call {
	_c.Call.Return(run)
	return _c
}

// Void provides a mock function with given fields: ctx, id, reason
func (_m *MockRepository) Void(ctx context.Context, id uuid.UUID, reason string) (entity.Draw, error) {
	ret := _m.Called(ctx, id, reason)

	if len(ret) == 0 {
		panic("no return value specified for Void")
	}

	var r0 entity.Draw
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (entity.Draw, error)); ok {
		return rf(ctx, id, reason)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) entity.Draw); ok {
		r0 = rf(ctx, id, reason)
	} else {
		r0 = ret.Get(0).(entity.Draw)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, id, reason)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Void_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Void'
type MockRepository_Void_Call struct {
	*mock.Call
}

// Void is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - reason string
func (_e *MockRepository_Expecter) Void(ctx interface{}, id interface{}, reason interface{}) *MockRepository_Void_Call {
	return &MockRepository_Void_Call{Call: _e.mock.On("Void", ctx, id, reason)}
}

func (_c *MockRepository_Void_Call) Run(run func(ctx context.Context, id uuid.UUID, reason string)) *MockRepository_Void_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_Void_Call) Return(_a0 entity.Draw, _a1 error) *MockRepository_Void_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Void_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (entity.Draw, error)) *MockRepository_Void_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
