// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "application/internal/entity"
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockUsecasePlaceholder is an autogenerated mock type for the UsecasePlaceholder type
type MockUsecasePlaceholder struct {
	mock.Mock
}

type MockUsecasePlaceholder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecasePlaceholder) EXPECT() *MockUsecasePlaceholder_Expecter {
	return &MockUsecasePlaceholder_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, name
func (_m *MockUsecasePlaceholder) Create(ctx context.Context, name string) (uuid.UUID, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (uuid.UUID, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) uuid.UUID); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecasePlaceholder_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUsecasePlaceholder_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockUsecasePlaceholder_Expecter) Create(ctx interface{}, name interface{}) *MockUsecasePlaceholder_Create_Call {
	return &MockUsecasePlaceholder_Create_Call{Call: _e.mock.On("Create", ctx, name)}
}

func (_c *MockUsecasePlaceholder_Create_Call) Run(run func(ctx context.Context, name string)) *MockUsecasePlaceholder_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUsecasePlaceholder_Create_Call) Return(_a0 uuid.UUID, _a1 error) *MockUsecasePlaceholder_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecasePlaceholder_Create_Call) RunAndReturn(run func(context.Context, string) (uuid.UUID, error)) *MockUsecasePlaceholder_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockUsecasePlaceholder) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsecasePlaceholder_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUsecasePlaceholder_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsecasePlaceholder_Expecter) Delete(ctx interface{}, id interface{}) *MockUsecasePlaceholder_Delete_Call {
	return &MockUsecasePlaceholder_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockUsecasePlaceholder_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsecasePlaceholder_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecasePlaceholder_Delete_Call) Return(_a0 error) *MockUsecasePlaceholder_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsecasePlaceholder_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockUsecasePlaceholder_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockUsecasePlaceholder) Get(ctx context.Context, id uuid.UUID) (entity.Placeholder, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.Placeholder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Placeholder, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Placeholder); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Placeholder)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecasePlaceholder_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUsecasePlaceholder_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsecasePlaceholder_Expecter) Get(ctx interface{}, id interface{}) *MockUsecasePlaceholder_Get_Call {
	return &MockUsecasePlaceholder_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockUsecasePlaceholder_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsecasePlaceholder_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecasePlaceholder_Get_Call) Return(_a0 entity.Placeholder, _a1 error) *MockUsecasePlaceholder_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecasePlaceholder_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Placeholder, error)) *MockUsecasePlaceholder_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockUsecasePlaceholder) List(ctx context.Context) ([]entity.Placeholder, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Placeholder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.Placeholder, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Placeholder); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Placeholder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecasePlaceholder_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUsecasePlaceholder_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUsecasePlaceholder_Expecter) List(ctx interface{}) *MockUsecasePlaceholder_List_Call {
	return &MockUsecasePlaceholder_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockUsecasePlaceholder_List_Call) Run(run func(ctx context.Context)) *MockUsecasePlaceholder_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUsecasePlaceholder_List_Call) Return(_a0 []entity.Placeholder, _a1 error) *MockUsecasePlaceholder_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecasePlaceholder_List_Call) RunAndReturn(run func(context.Context) ([]entity.Placeholder, error)) *MockUsecasePlaceholder_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, name
func (_m *MockUsecasePlaceholder) Update(ctx context.Context, id uuid.UUID, name string) error {
	ret := _m.Called(ctx, id, name)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, id, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsecasePlaceholder_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUsecasePlaceholder_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - name string
func (_e *MockUsecasePlaceholder_Expecter) Update(ctx interface{}, id interface{}, name interface{}) *MockUsecasePlaceholder_Update_Call {
	return &MockUsecasePlaceholder_Update_Call{Call: _e.mock.On("Update", ctx, id, name)}
}

func (_c *MockUsecasePlaceholder_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, name string)) *MockUsecasePlaceholder_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockUsecasePlaceholder_Update_Call) Return(_a0 error) *MockUsecasePlaceholder_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsecasePlaceholder_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockUsecasePlaceholder_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecasePlaceholder creates a new instance of MockUsecasePlaceholder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecasePlaceholder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecasePlaceholder {
	mock := &MockUsecasePlaceholder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
