// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "application/internal/media/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, m
func (_m *MockRepository) Create(ctx context.Context, m entity.Media) (entity.Media, error) {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.Media
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Media) (entity.Media, error)); ok {
		return rf(ctx, m)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Media) entity.Media); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Get(0).(entity.Media)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Media) error); ok {
		r1 = rf(ctx, m)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - m entity.Media
func (_e *MockRepository_Expecter) Create(ctx interface{}, m interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, m)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, m entity.Media)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Media))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 entity.Media, _a1 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, entity.Media) (entity.Media, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockRepository) Get(ctx context.Context, id uuid.UUID) (entity.Media, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.Media
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Media, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Media); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Media)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) Get(ctx interface{}, id interface{}) *MockRepository_Get_Call {
	return &MockRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_Get_Call) Return(_a0 entity.Media, _a1 error) *MockRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Media, error)) *MockRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListByOwner provides a mock function with given fields: ctx, ownerType, ownerID
func (_m *MockRepository) ListByOwner(ctx context.Context, ownerType string, ownerID uuid.UUID) ([]entity.Media, error) {
	ret := _m.Called(ctx, ownerType, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for ListByOwner")
	}

	var r0 []entity.Media
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) ([]entity.Media, error)); ok {
		return rf(ctx, ownerType, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) []entity.Media); ok {
		r0 = rf(ctx, ownerType, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Media)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = rf(ctx, ownerType, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByOwner'
type MockRepository_ListByOwner_Call struct {
	*mock.Call
}

// ListByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerType string
//   - ownerID uuid.UUID
func (_e *MockRepository_Expecter) ListByOwner(ctx interface{}, ownerType interface{}, ownerID interface{}) *MockRepository_ListByOwner_Call {
	return &MockRepository_ListByOwner_Call{Call: _e.mock.On("ListByOwner", ctx, ownerType, ownerID)}
}

func (_c *MockRepository_ListByOwner_Call) Run(run func(ctx context.Context, ownerType string, ownerID uuid.UUID)) *MockRepository_ListByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_ListByOwner_Call) Return(_a0 []entity.Media, _a1 error) *MockRepository_ListByOwner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListByOwner_Call) RunAndReturn(run func(context.Context, string, uuid.UUID) ([]entity.Media, error)) *MockRepository_ListByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
