// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	biz "application/internal/media/biz"
	context "context"

	entity "application/internal/media/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, m
func (_m *MockRepository) Create(ctx context.Context, m entity.Media) (entity.Media, error) {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.Media
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Media) (entity.Media, error)); ok {
		return rf(ctx, m)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Media) entity.Media); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Get(0).(entity.Media)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Media) error); ok {
		r1 = rf(ctx, m)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - m entity.Media
func (_e *MockRepository_Expecter) Create(ctx interface{}, m interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, m)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, m entity.Media)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Media))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 entity.Media, _a1 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, entity.Media) (entity.Media, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(_a0 error) *MockRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockRepository) Get(ctx context.Context, id uuid.UUID) (entity.Media, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.Media
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Media, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Media); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Media)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) Get(ctx interface{}, id interface{}) *MockRepository_Get_Call {
	return &MockRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_Get_Call) Return(_a0 entity.Media, _a1 error) *MockRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Media, error)) *MockRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListAll provides a mock function with given fields: ctx, limit, offset
func (_m *MockRepository) ListAll(ctx context.Context, limit int, offset int) (biz.MediaPage, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 biz.MediaPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (biz.MediaPage, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) biz.MediaPage); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		r0 = ret.Get(0).(biz.MediaPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type MockRepository_ListAll_Call struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockRepository_Expecter) ListAll(ctx interface{}, limit interface{}, offset interface{}) *MockRepository_ListAll_Call {
	return &MockRepository_ListAll_Call{Call: _e.mock.On("ListAll", ctx, limit, offset)}
}

func (_c *MockRepository_ListAll_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockRepository_ListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockRepository_ListAll_Call) Return(_a0 biz.MediaPage, _a1 error) *MockRepository_ListAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListAll_Call) RunAndReturn(run func(context.Context, int, int) (biz.MediaPage, error)) *MockRepository_ListAll_Call {
	_c.Call.Return(run)
	return _c
}

// ListByOwner provides a mock function with given fields: ctx, ownerType, ownerID
func (_m *MockRepository) ListByOwner(ctx context.Context, ownerType string, ownerID uuid.UUID) ([]entity.Media, error) {
	ret := _m.Called(ctx, ownerType, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for ListByOwner")
	}

	var r0 []entity.Media
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) ([]entity.Media, error)); ok {
		return rf(ctx, ownerType, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) []entity.Media); ok {
		r0 = rf(ctx, ownerType, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Media)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = rf(ctx, ownerType, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByOwner'
type MockRepository_ListByOwner_Call struct {
	*mock.Call
}

// ListByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerType string
//   - ownerID uuid.UUID
func (_e *MockRepository_Expecter) ListByOwner(ctx interface{}, ownerType interface{}, ownerID interface{}) *MockRepository_ListByOwner_Call {
	return &MockRepository_ListByOwner_Call{Call: _e.mock.On("ListByOwner", ctx, ownerType, ownerID)}
}

func (_c *MockRepository_ListByOwner_Call) Run(run func(ctx context.Context, ownerType string, ownerID uuid.UUID)) *MockRepository_ListByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_ListByOwner_Call) Return(_a0 []entity.Media, _a1 error) *MockRepository_ListByOwner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListByOwner_Call) RunAndReturn(run func(context.Context, string, uuid.UUID) ([]entity.Media, error)) *MockRepository_ListByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, in
func (_m *MockRepository) Update(ctx context.Context, id uuid.UUID, in biz.UpdateInput) (entity.Media, error) {
	ret := _m.Called(ctx, id, in)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 entity.Media
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, biz.UpdateInput) (entity.Media, error)); ok {
		return rf(ctx, id, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, biz.UpdateInput) entity.Media); ok {
		r0 = rf(ctx, id, in)
	} else {
		r0 = ret.Get(0).(entity.Media)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, biz.UpdateInput) error); ok {
		r1 = rf(ctx, id, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - in biz.UpdateInput
func (_e *MockRepository_Expecter) Update(ctx interface{}, id interface{}, in interface{}) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, in)}
}

func (_c *MockRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, in biz.UpdateInput)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(biz.UpdateInput))
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(_a0 entity.Media, _a1 error) *MockRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, biz.UpdateInput) (entity.Media, error)) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
