// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	biz "application/internal/media/biz"
	entity "application/internal/media/entity"
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockUsecaseMedia is an autogenerated mock type for the UsecaseMedia type
type MockUsecaseMedia struct {
	mock.Mock
}

type MockUsecaseMedia_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecaseMedia) EXPECT() *MockUsecaseMedia_Expecter {
	return &MockUsecaseMedia_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockUsecaseMedia) Get(ctx context.Context, id uuid.UUID) (biz.MediaWithURL, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 biz.MediaWithURL
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (biz.MediaWithURL, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) biz.MediaWithURL); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(biz.MediaWithURL)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseMedia_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUsecaseMedia_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsecaseMedia_Expecter) Get(ctx interface{}, id interface{}) *MockUsecaseMedia_Get_Call {
	return &MockUsecaseMedia_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockUsecaseMedia_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsecaseMedia_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseMedia_Get_Call) Return(_a0 biz.MediaWithURL, _a1 error) *MockUsecaseMedia_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseMedia_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (biz.MediaWithURL, error)) *MockUsecaseMedia_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListByOwner provides a mock function with given fields: ctx, ownerType, ownerID
func (_m *MockUsecaseMedia) ListByOwner(ctx context.Context, ownerType string, ownerID uuid.UUID) ([]entity.Media, error) {
	ret := _m.Called(ctx, ownerType, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for ListByOwner")
	}

	var r0 []entity.Media
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) ([]entity.Media, error)); ok {
		return rf(ctx, ownerType, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) []entity.Media); ok {
		r0 = rf(ctx, ownerType, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Media)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = rf(ctx, ownerType, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseMedia_ListByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByOwner'
type MockUsecaseMedia_ListByOwner_Call struct {
	*mock.Call
}

// ListByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerType string
//   - ownerID uuid.UUID
func (_e *MockUsecaseMedia_Expecter) ListByOwner(ctx interface{}, ownerType interface{}, ownerID interface{}) *MockUsecaseMedia_ListByOwner_Call {
	return &MockUsecaseMedia_ListByOwner_Call{Call: _e.mock.On("ListByOwner", ctx, ownerType, ownerID)}
}

func (_c *MockUsecaseMedia_ListByOwner_Call) Run(run func(ctx context.Context, ownerType string, ownerID uuid.UUID)) *MockUsecaseMedia_ListByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseMedia_ListByOwner_Call) Return(_a0 []entity.Media, _a1 error) *MockUsecaseMedia_ListByOwner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseMedia_ListByOwner_Call) RunAndReturn(run func(context.Context, string, uuid.UUID) ([]entity.Media, error)) *MockUsecaseMedia_ListByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: ctx, in
func (_m *MockUsecaseMedia) Upload(ctx context.Context, in biz.UploadInput) (entity.Media, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 entity.Media
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.UploadInput) (entity.Media, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, biz.UploadInput) entity.Media); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(entity.Media)
	}

	if rf, ok := ret.Get(1).(func(context.Context, biz.UploadInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseMedia_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockUsecaseMedia_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - in biz.UploadInput
func (_e *MockUsecaseMedia_Expecter) Upload(ctx interface{}, in interface{}) *MockUsecaseMedia_Upload_Call {
	return &MockUsecaseMedia_Upload_Call{Call: _e.mock.On("Upload", ctx, in)}
}

func (_c *MockUsecaseMedia_Upload_Call) Run(run func(ctx context.Context, in biz.UploadInput)) *MockUsecaseMedia_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.UploadInput))
	})
	return _c
}

func (_c *MockUsecaseMedia_Upload_Call) Return(_a0 entity.Media, _a1 error) *MockUsecaseMedia_Upload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseMedia_Upload_Call) RunAndReturn(run func(context.Context, biz.UploadInput) (entity.Media, error)) *MockUsecaseMedia_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecaseMedia creates a new instance of MockUsecaseMedia. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecaseMedia(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecaseMedia {
	mock := &MockUsecaseMedia{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
