// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "application/internal/competition/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUsecaseContent is an autogenerated mock type for the UsecaseContent type
type MockUsecaseContent struct {
	mock.Mock
}

type MockUsecaseContent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecaseContent) EXPECT() *MockUsecaseContent_Expecter {
	return &MockUsecaseContent_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function with given fields: ctx
func (_m *MockUsecaseContent) GetAll(ctx context.Context) ([]entity.SiteContent, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []entity.SiteContent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.SiteContent, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.SiteContent); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.SiteContent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseContent_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockUsecaseContent_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUsecaseContent_Expecter) GetAll(ctx interface{}) *MockUsecaseContent_GetAll_Call {
	return &MockUsecaseContent_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockUsecaseContent_GetAll_Call) Run(run func(ctx context.Context)) *MockUsecaseContent_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUsecaseContent_GetAll_Call) Return(_a0 []entity.SiteContent, _a1 error) *MockUsecaseContent_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseContent_GetAll_Call) RunAndReturn(run func(context.Context) ([]entity.SiteContent, error)) *MockUsecaseContent_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, key, value
func (_m *MockUsecaseContent) Upsert(ctx context.Context, key string, value string) (entity.SiteContent, error) {
	ret := _m.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 entity.SiteContent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (entity.SiteContent, error)); ok {
		return rf(ctx, key, value)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) entity.SiteContent); ok {
		r0 = rf(ctx, key, value)
	} else {
		r0 = ret.Get(0).(entity.SiteContent)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, key, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseContent_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockUsecaseContent_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
func (_e *MockUsecaseContent_Expecter) Upsert(ctx interface{}, key interface{}, value interface{}) *MockUsecaseContent_Upsert_Call {
	return &MockUsecaseContent_Upsert_Call{Call: _e.mock.On("Upsert", ctx, key, value)}
}

func (_c *MockUsecaseContent_Upsert_Call) Run(run func(ctx context.Context, key string, value string)) *MockUsecaseContent_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUsecaseContent_Upsert_Call) Return(_a0 entity.SiteContent, _a1 error) *MockUsecaseContent_Upsert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseContent_Upsert_Call) RunAndReturn(run func(context.Context, string, string) (entity.SiteContent, error)) *MockUsecaseContent_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecaseContent creates a new instance of MockUsecaseContent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecaseContent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecaseContent {
	mock := &MockUsecaseContent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
