// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "application/internal/competition/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRepositoryCategory is an autogenerated mock type for the RepositoryCategory type
type MockRepositoryCategory struct {
	mock.Mock
}

type MockRepositoryCategory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryCategory) EXPECT() *MockRepositoryCategory_Expecter {
	return &MockRepositoryCategory_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, c
func (_m *MockRepositoryCategory) Create(ctx context.Context, c entity.Category) (entity.Category, error) {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Category) (entity.Category, error)); ok {
		return rf(ctx, c)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Category) entity.Category); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Get(0).(entity.Category)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Category) error); ok {
		r1 = rf(ctx, c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryCategory_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepositoryCategory_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - c entity.Category
func (_e *MockRepositoryCategory_Expecter) Create(ctx interface{}, c interface{}) *MockRepositoryCategory_Create_Call {
	return &MockRepositoryCategory_Create_Call{Call: _e.mock.On("Create", ctx, c)}
}

func (_c *MockRepositoryCategory_Create_Call) Run(run func(ctx context.Context, c entity.Category)) *MockRepositoryCategory_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Category))
	})
	return _c
}

func (_c *MockRepositoryCategory_Create_Call) Return(_a0 entity.Category, _a1 error) *MockRepositoryCategory_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryCategory_Create_Call) RunAndReturn(run func(context.Context, entity.Category) (entity.Category, error)) *MockRepositoryCategory_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id, reassignTo
func (_m *MockRepositoryCategory) Delete(ctx context.Context, id uuid.UUID, reassignTo *uuid.UUID) error {
	ret := _m.Called(ctx, id, reassignTo)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID) error); ok {
		r0 = rf(ctx, id, reassignTo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryCategory_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepositoryCategory_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - reassignTo *uuid.UUID
func (_e *MockRepositoryCategory_Expecter) Delete(ctx interface{}, id interface{}, reassignTo interface{}) *MockRepositoryCategory_Delete_Call {
	return &MockRepositoryCategory_Delete_Call{Call: _e.mock.On("Delete", ctx, id, reassignTo)}
}

func (_c *MockRepositoryCategory_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID, reassignTo *uuid.UUID)) *MockRepositoryCategory_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*uuid.UUID))
	})
	return _c
}

func (_c *MockRepositoryCategory_Delete_Call) Return(_a0 error) *MockRepositoryCategory_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryCategory_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, *uuid.UUID) error) *MockRepositoryCategory_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockRepositoryCategory) Get(ctx context.Context, id uuid.UUID) (entity.Category, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Category, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Category); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Category)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryCategory_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepositoryCategory_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepositoryCategory_Expecter) Get(ctx interface{}, id interface{}) *MockRepositoryCategory_Get_Call {
	return &MockRepositoryCategory_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockRepositoryCategory_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepositoryCategory_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepositoryCategory_Get_Call) Return(_a0 entity.Category, _a1 error) *MockRepositoryCategory_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryCategory_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Category, error)) *MockRepositoryCategory_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockRepositoryCategory) List(ctx context.Context) ([]entity.Category, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.Category, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Category); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryCategory_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepositoryCategory_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepositoryCategory_Expecter) List(ctx interface{}) *MockRepositoryCategory_List_Call {
	return &MockRepositoryCategory_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockRepositoryCategory_List_Call) Run(run func(ctx context.Context)) *MockRepositoryCategory_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepositoryCategory_List_Call) Return(_a0 []entity.Category, _a1 error) *MockRepositoryCategory_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryCategory_List_Call) RunAndReturn(run func(context.Context) ([]entity.Category, error)) *MockRepositoryCategory_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, c
func (_m *MockRepositoryCategory) Update(ctx context.Context, c entity.Category) (entity.Category, error) {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 entity.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Category) (entity.Category, error)); ok {
		return rf(ctx, c)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Category) entity.Category); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Get(0).(entity.Category)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Category) error); ok {
		r1 = rf(ctx, c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryCategory_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepositoryCategory_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - c entity.Category
func (_e *MockRepositoryCategory_Expecter) Update(ctx interface{}, c interface{}) *MockRepositoryCategory_Update_Call {
	return &MockRepositoryCategory_Update_Call{Call: _e.mock.On("Update", ctx, c)}
}

func (_c *MockRepositoryCategory_Update_Call) Run(run func(ctx context.Context, c entity.Category)) *MockRepositoryCategory_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Category))
	})
	return _c
}

func (_c *MockRepositoryCategory_Update_Call) Return(_a0 entity.Category, _a1 error) *MockRepositoryCategory_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryCategory_Update_Call) RunAndReturn(run func(context.Context, entity.Category) (entity.Category, error)) *MockRepositoryCategory_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryCategory creates a new instance of MockRepositoryCategory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryCategory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryCategory {
	mock := &MockRepositoryCategory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
