// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	biz "application/internal/competition/biz"
	context "context"

	entity "application/internal/competition/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUsecaseCategory is an autogenerated mock type for the UsecaseCategory type
type MockUsecaseCategory struct {
	mock.Mock
}

type MockUsecaseCategory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecaseCategory) EXPECT() *MockUsecaseCategory_Expecter {
	return &MockUsecaseCategory_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, in
func (_m *MockUsecaseCategory) Create(ctx context.Context, in biz.CategoryInput) (entity.Category, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.CategoryInput) (entity.Category, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, biz.CategoryInput) entity.Category); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(entity.Category)
	}

	if rf, ok := ret.Get(1).(func(context.Context, biz.CategoryInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseCategory_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUsecaseCategory_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - in biz.CategoryInput
func (_e *MockUsecaseCategory_Expecter) Create(ctx interface{}, in interface{}) *MockUsecaseCategory_Create_Call {
	return &MockUsecaseCategory_Create_Call{Call: _e.mock.On("Create", ctx, in)}
}

func (_c *MockUsecaseCategory_Create_Call) Run(run func(ctx context.Context, in biz.CategoryInput)) *MockUsecaseCategory_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.CategoryInput))
	})
	return _c
}

func (_c *MockUsecaseCategory_Create_Call) Return(_a0 entity.Category, _a1 error) *MockUsecaseCategory_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseCategory_Create_Call) RunAndReturn(run func(context.Context, biz.CategoryInput) (entity.Category, error)) *MockUsecaseCategory_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id, reassignTo
func (_m *MockUsecaseCategory) Delete(ctx context.Context, id uuid.UUID, reassignTo *uuid.UUID) error {
	ret := _m.Called(ctx, id, reassignTo)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID) error); ok {
		r0 = rf(ctx, id, reassignTo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsecaseCategory_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUsecaseCategory_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - reassignTo *uuid.UUID
func (_e *MockUsecaseCategory_Expecter) Delete(ctx interface{}, id interface{}, reassignTo interface{}) *MockUsecaseCategory_Delete_Call {
	return &MockUsecaseCategory_Delete_Call{Call: _e.mock.On("Delete", ctx, id, reassignTo)}
}

func (_c *MockUsecaseCategory_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID, reassignTo *uuid.UUID)) *MockUsecaseCategory_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseCategory_Delete_Call) Return(_a0 error) *MockUsecaseCategory_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsecaseCategory_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, *uuid.UUID) error) *MockUsecaseCategory_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockUsecaseCategory) List(ctx context.Context) ([]entity.Category, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.Category, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Category); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseCategory_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUsecaseCategory_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUsecaseCategory_Expecter) List(ctx interface{}) *MockUsecaseCategory_List_Call {
	return &MockUsecaseCategory_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockUsecaseCategory_List_Call) Run(run func(ctx context.Context)) *MockUsecaseCategory_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUsecaseCategory_List_Call) Return(_a0 []entity.Category, _a1 error) *MockUsecaseCategory_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseCategory_List_Call) RunAndReturn(run func(context.Context) ([]entity.Category, error)) *MockUsecaseCategory_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, in
func (_m *MockUsecaseCategory) Update(ctx context.Context, id uuid.UUID, in biz.CategoryInput) (entity.Category, error) {
	ret := _m.Called(ctx, id, in)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 entity.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, biz.CategoryInput) (entity.Category, error)); ok {
		return rf(ctx, id, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, biz.CategoryInput) entity.Category); ok {
		r0 = rf(ctx, id, in)
	} else {
		r0 = ret.Get(0).(entity.Category)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, biz.CategoryInput) error); ok {
		r1 = rf(ctx, id, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseCategory_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUsecaseCategory_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - in biz.CategoryInput
func (_e *MockUsecaseCategory_Expecter) Update(ctx interface{}, id interface{}, in interface{}) *MockUsecaseCategory_Update_Call {
	return &MockUsecaseCategory_Update_Call{Call: _e.mock.On("Update", ctx, id, in)}
}

func (_c *MockUsecaseCategory_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, in biz.CategoryInput)) *MockUsecaseCategory_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(biz.CategoryInput))
	})
	return _c
}

func (_c *MockUsecaseCategory_Update_Call) Return(_a0 entity.Category, _a1 error) *MockUsecaseCategory_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseCategory_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, biz.CategoryInput) (entity.Category, error)) *MockUsecaseCategory_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecaseCategory creates a new instance of MockUsecaseCategory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecaseCategory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecaseCategory {
	mock := &MockUsecaseCategory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
