// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	biz "application/internal/competition/biz"
	context "context"

	entity "application/internal/competition/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUsecaseCompetition is an autogenerated mock type for the UsecaseCompetition type
type MockUsecaseCompetition struct {
	mock.Mock
}

type MockUsecaseCompetition_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecaseCompetition) EXPECT() *MockUsecaseCompetition_Expecter {
	return &MockUsecaseCompetition_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, in
func (_m *MockUsecaseCompetition) Create(ctx context.Context, in biz.CreateInput) (entity.Competition, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.Competition
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.CreateInput) (entity.Competition, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, biz.CreateInput) entity.Competition); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(entity.Competition)
	}

	if rf, ok := ret.Get(1).(func(context.Context, biz.CreateInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseCompetition_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUsecaseCompetition_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - in biz.CreateInput
func (_e *MockUsecaseCompetition_Expecter) Create(ctx interface{}, in interface{}) *MockUsecaseCompetition_Create_Call {
	return &MockUsecaseCompetition_Create_Call{Call: _e.mock.On("Create", ctx, in)}
}

func (_c *MockUsecaseCompetition_Create_Call) Run(run func(ctx context.Context, in biz.CreateInput)) *MockUsecaseCompetition_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.CreateInput))
	})
	return _c
}

func (_c *MockUsecaseCompetition_Create_Call) Return(_a0 entity.Competition, _a1 error) *MockUsecaseCompetition_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseCompetition_Create_Call) RunAndReturn(run func(context.Context, biz.CreateInput) (entity.Competition, error)) *MockUsecaseCompetition_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockUsecaseCompetition) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsecaseCompetition_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUsecaseCompetition_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsecaseCompetition_Expecter) Delete(ctx interface{}, id interface{}) *MockUsecaseCompetition_Delete_Call {
	return &MockUsecaseCompetition_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockUsecaseCompetition_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsecaseCompetition_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseCompetition_Delete_Call) Return(_a0 error) *MockUsecaseCompetition_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsecaseCompetition_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockUsecaseCompetition_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockUsecaseCompetition) Get(ctx context.Context, id uuid.UUID) (entity.Competition, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.Competition
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Competition, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Competition); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Competition)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseCompetition_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUsecaseCompetition_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsecaseCompetition_Expecter) Get(ctx interface{}, id interface{}) *MockUsecaseCompetition_Get_Call {
	return &MockUsecaseCompetition_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockUsecaseCompetition_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsecaseCompetition_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseCompetition_Get_Call) Return(_a0 entity.Competition, _a1 error) *MockUsecaseCompetition_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseCompetition_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Competition, error)) *MockUsecaseCompetition_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockUsecaseCompetition) List(ctx context.Context, filter biz.ListFilter) ([]entity.Competition, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Competition
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.ListFilter) ([]entity.Competition, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, biz.ListFilter) []entity.Competition); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Competition)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, biz.ListFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseCompetition_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUsecaseCompetition_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter biz.ListFilter
func (_e *MockUsecaseCompetition_Expecter) List(ctx interface{}, filter interface{}) *MockUsecaseCompetition_List_Call {
	return &MockUsecaseCompetition_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockUsecaseCompetition_List_Call) Run(run func(ctx context.Context, filter biz.ListFilter)) *MockUsecaseCompetition_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.ListFilter))
	})
	return _c
}

func (_c *MockUsecaseCompetition_List_Call) Return(_a0 []entity.Competition, _a1 error) *MockUsecaseCompetition_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseCompetition_List_Call) RunAndReturn(run func(context.Context, biz.ListFilter) ([]entity.Competition, error)) *MockUsecaseCompetition_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, in
func (_m *MockUsecaseCompetition) Update(ctx context.Context, id uuid.UUID, in biz.UpdateInput) (entity.Competition, error) {
	ret := _m.Called(ctx, id, in)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 entity.Competition
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, biz.UpdateInput) (entity.Competition, error)); ok {
		return rf(ctx, id, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, biz.UpdateInput) entity.Competition); ok {
		r0 = rf(ctx, id, in)
	} else {
		r0 = ret.Get(0).(entity.Competition)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, biz.UpdateInput) error); ok {
		r1 = rf(ctx, id, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseCompetition_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUsecaseCompetition_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - in biz.UpdateInput
func (_e *MockUsecaseCompetition_Expecter) Update(ctx interface{}, id interface{}, in interface{}) *MockUsecaseCompetition_Update_Call {
	return &MockUsecaseCompetition_Update_Call{Call: _e.mock.On("Update", ctx, id, in)}
}

func (_c *MockUsecaseCompetition_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, in biz.UpdateInput)) *MockUsecaseCompetition_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(biz.UpdateInput))
	})
	return _c
}

func (_c *MockUsecaseCompetition_Update_Call) Return(_a0 entity.Competition, _a1 error) *MockUsecaseCompetition_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseCompetition_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, biz.UpdateInput) (entity.Competition, error)) *MockUsecaseCompetition_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecaseCompetition creates a new instance of MockUsecaseCompetition. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecaseCompetition(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecaseCompetition {
	mock := &MockUsecaseCompetition{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
