// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	biz "application/internal/user/biz"
	context "context"

	entity "application/internal/user/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUsecaseTicket is an autogenerated mock type for the UsecaseTicket type
type MockUsecaseTicket struct {
	mock.Mock
}

type MockUsecaseTicket_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecaseTicket) EXPECT() *MockUsecaseTicket_Expecter {
	return &MockUsecaseTicket_Expecter{mock: &_m.Mock}
}

// ListByUser provides a mock function with given fields: ctx, userID
func (_m *MockUsecaseTicket) ListByUser(ctx context.Context, userID uuid.UUID) ([]entity.Ticket, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []entity.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entity.Ticket, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entity.Ticket); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseTicket_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockUsecaseTicket_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUsecaseTicket_Expecter) ListByUser(ctx interface{}, userID interface{}) *MockUsecaseTicket_ListByUser_Call {
	return &MockUsecaseTicket_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *MockUsecaseTicket_ListByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUsecaseTicket_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseTicket_ListByUser_Call) Return(_a0 []entity.Ticket, _a1 error) *MockUsecaseTicket_ListByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseTicket_ListByUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]entity.Ticket, error)) *MockUsecaseTicket_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Purchase provides a mock function with given fields: ctx, in
func (_m *MockUsecaseTicket) Purchase(ctx context.Context, in biz.PurchaseInput) (biz.PurchaseResult, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Purchase")
	}

	var r0 biz.PurchaseResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.PurchaseInput) (biz.PurchaseResult, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, biz.PurchaseInput) biz.PurchaseResult); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(biz.PurchaseResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, biz.PurchaseInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseTicket_Purchase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Purchase'
type MockUsecaseTicket_Purchase_Call struct {
	*mock.Call
}

// Purchase is a helper method to define mock.On call
//   - ctx context.Context
//   - in biz.PurchaseInput
func (_e *MockUsecaseTicket_Expecter) Purchase(ctx interface{}, in interface{}) *MockUsecaseTicket_Purchase_Call {
	return &MockUsecaseTicket_Purchase_Call{Call: _e.mock.On("Purchase", ctx, in)}
}

func (_c *MockUsecaseTicket_Purchase_Call) Run(run func(ctx context.Context, in biz.PurchaseInput)) *MockUsecaseTicket_Purchase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.PurchaseInput))
	})
	return _c
}

func (_c *MockUsecaseTicket_Purchase_Call) Return(_a0 biz.PurchaseResult, _a1 error) *MockUsecaseTicket_Purchase_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseTicket_Purchase_Call) RunAndReturn(run func(context.Context, biz.PurchaseInput) (biz.PurchaseResult, error)) *MockUsecaseTicket_Purchase_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecaseTicket creates a new instance of MockUsecaseTicket. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecaseTicket(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecaseTicket {
	mock := &MockUsecaseTicket{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
