// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	biz "application/internal/user/biz"
	context "context"

	entity "application/internal/user/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUsecaseUser is an autogenerated mock type for the UsecaseUser type
type MockUsecaseUser struct {
	mock.Mock
}

type MockUsecaseUser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecaseUser) EXPECT() *MockUsecaseUser_Expecter {
	return &MockUsecaseUser_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockUsecaseUser) Get(ctx context.Context, id uuid.UUID) (entity.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseUser_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUsecaseUser_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsecaseUser_Expecter) Get(ctx interface{}, id interface{}) *MockUsecaseUser_Get_Call {
	return &MockUsecaseUser_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockUsecaseUser_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsecaseUser_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseUser_Get_Call) Return(_a0 entity.User, _a1 error) *MockUsecaseUser_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseUser_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.User, error)) *MockUsecaseUser_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockUsecaseUser) List(ctx context.Context, filter biz.UserListFilter) (biz.UserPage, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 biz.UserPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.UserListFilter) (biz.UserPage, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, biz.UserListFilter) biz.UserPage); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(biz.UserPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, biz.UserListFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseUser_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUsecaseUser_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter biz.UserListFilter
func (_e *MockUsecaseUser_Expecter) List(ctx interface{}, filter interface{}) *MockUsecaseUser_List_Call {
	return &MockUsecaseUser_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockUsecaseUser_List_Call) Run(run func(ctx context.Context, filter biz.UserListFilter)) *MockUsecaseUser_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.UserListFilter))
	})
	return _c
}

func (_c *MockUsecaseUser_List_Call) Return(_a0 biz.UserPage, _a1 error) *MockUsecaseUser_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseUser_List_Call) RunAndReturn(run func(context.Context, biz.UserListFilter) (biz.UserPage, error)) *MockUsecaseUser_List_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, name, email
func (_m *MockUsecaseUser) Register(ctx context.Context, name string, email string) (entity.User, error) {
	ret := _m.Called(ctx, name, email)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (entity.User, error)); ok {
		return rf(ctx, name, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) entity.User); ok {
		r0 = rf(ctx, name, email)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseUser_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockUsecaseUser_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - email string
func (_e *MockUsecaseUser_Expecter) Register(ctx interface{}, name interface{}, email interface{}) *MockUsecaseUser_Register_Call {
	return &MockUsecaseUser_Register_Call{Call: _e.mock.On("Register", ctx, name, email)}
}

func (_c *MockUsecaseUser_Register_Call) Run(run func(ctx context.Context, name string, email string)) *MockUsecaseUser_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUsecaseUser_Register_Call) Return(_a0 entity.User, _a1 error) *MockUsecaseUser_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseUser_Register_Call) RunAndReturn(run func(context.Context, string, string) (entity.User, error)) *MockUsecaseUser_Register_Call {
	_c.Call.Return(run)
	return _c
}

// SetActive provides a mock function with given fields: ctx, id, active
func (_m *MockUsecaseUser) SetActive(ctx context.Context, id uuid.UUID, active bool) (entity.User, error) {
	ret := _m.Called(ctx, id, active)

	if len(ret) == 0 {
		panic("no return value specified for SetActive")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) (entity.User, error)); ok {
		return rf(ctx, id, active)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) entity.User); ok {
		r0 = rf(ctx, id, active)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, bool) error); ok {
		r1 = rf(ctx, id, active)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseUser_SetActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetActive'
type MockUsecaseUser_SetActive_Call struct {
	*mock.Call
}

// SetActive is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - active bool
func (_e *MockUsecaseUser_Expecter) SetActive(ctx interface{}, id interface{}, active interface{}) *MockUsecaseUser_SetActive_Call {
	return &MockUsecaseUser_SetActive_Call{Call: _e.mock.On("SetActive", ctx, id, active)}
}

func (_c *MockUsecaseUser_SetActive_Call) Run(run func(ctx context.Context, id uuid.UUID, active bool)) *MockUsecaseUser_SetActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool))
	})
	return _c
}

func (_c *MockUsecaseUser_SetActive_Call) Return(_a0 entity.User, _a1 error) *MockUsecaseUser_SetActive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseUser_SetActive_Call) RunAndReturn(run func(context.Context, uuid.UUID, bool) (entity.User, error)) *MockUsecaseUser_SetActive_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, name, email
func (_m *MockUsecaseUser) Update(ctx context.Context, id uuid.UUID, name string, email string) (entity.User, error) {
	ret := _m.Called(ctx, id, name, email)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (entity.User, error)); ok {
		return rf(ctx, id, name, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) entity.User); ok {
		r0 = rf(ctx, id, name, email)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, id, name, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseUser_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUsecaseUser_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - name string
//   - email string
func (_e *MockUsecaseUser_Expecter) Update(ctx interface{}, id interface{}, name interface{}, email interface{}) *MockUsecaseUser_Update_Call {
	return &MockUsecaseUser_Update_Call{Call: _e.mock.On("Update", ctx, id, name, email)}
}

func (_c *MockUsecaseUser_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, name string, email string)) *MockUsecaseUser_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockUsecaseUser_Update_Call) Return(_a0 entity.User, _a1 error) *MockUsecaseUser_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseUser_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string) (entity.User, error)) *MockUsecaseUser_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecaseUser creates a new instance of MockUsecaseUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecaseUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecaseUser {
	mock := &MockUsecaseUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
