// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	biz "application/internal/user/biz"
	context "context"

	entity "application/internal/user/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRepositoryUser is an autogenerated mock type for the RepositoryUser type
type MockRepositoryUser struct {
	mock.Mock
}

type MockRepositoryUser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryUser) EXPECT() *MockRepositoryUser_Expecter {
	return &MockRepositoryUser_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, u
func (_m *MockRepositoryUser) Create(ctx context.Context, u entity.User) (entity.User, error) {
	ret := _m.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.User) (entity.User, error)); ok {
		return rf(ctx, u)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.User) entity.User); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.User) error); ok {
		r1 = rf(ctx, u)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryUser_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepositoryUser_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - u entity.User
func (_e *MockRepositoryUser_Expecter) Create(ctx interface{}, u interface{}) *MockRepositoryUser_Create_Call {
	return &MockRepositoryUser_Create_Call{Call: _e.mock.On("Create", ctx, u)}
}

func (_c *MockRepositoryUser_Create_Call) Run(run func(ctx context.Context, u entity.User)) *MockRepositoryUser_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.User))
	})
	return _c
}

func (_c *MockRepositoryUser_Create_Call) Return(_a0 entity.User, _a1 error) *MockRepositoryUser_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryUser_Create_Call) RunAndReturn(run func(context.Context, entity.User) (entity.User, error)) *MockRepositoryUser_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockRepositoryUser) Get(ctx context.Context, id uuid.UUID) (entity.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryUser_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepositoryUser_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepositoryUser_Expecter) Get(ctx interface{}, id interface{}) *MockRepositoryUser_Get_Call {
	return &MockRepositoryUser_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockRepositoryUser_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepositoryUser_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepositoryUser_Get_Call) Return(_a0 entity.User, _a1 error) *MockRepositoryUser_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryUser_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.User, error)) *MockRepositoryUser_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockRepositoryUser) List(ctx context.Context, filter biz.UserListFilter) (biz.UserPage, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 biz.UserPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.UserListFilter) (biz.UserPage, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, biz.UserListFilter) biz.UserPage); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(biz.UserPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, biz.UserListFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryUser_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepositoryUser_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter biz.UserListFilter
func (_e *MockRepositoryUser_Expecter) List(ctx interface{}, filter interface{}) *MockRepositoryUser_List_Call {
	return &MockRepositoryUser_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockRepositoryUser_List_Call) Run(run func(ctx context.Context, filter biz.UserListFilter)) *MockRepositoryUser_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.UserListFilter))
	})
	return _c
}

func (_c *MockRepositoryUser_List_Call) Return(_a0 biz.UserPage, _a1 error) *MockRepositoryUser_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryUser_List_Call) RunAndReturn(run func(context.Context, biz.UserListFilter) (biz.UserPage, error)) *MockRepositoryUser_List_Call {
	_c.Call.Return(run)
	return _c
}

// SetActive provides a mock function with given fields: ctx, id, active
func (_m *MockRepositoryUser) SetActive(ctx context.Context, id uuid.UUID, active bool) (entity.User, error) {
	ret := _m.Called(ctx, id, active)

	if len(ret) == 0 {
		panic("no return value specified for SetActive")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) (entity.User, error)); ok {
		return rf(ctx, id, active)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) entity.User); ok {
		r0 = rf(ctx, id, active)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, bool) error); ok {
		r1 = rf(ctx, id, active)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryUser_SetActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetActive'
type MockRepositoryUser_SetActive_Call struct {
	*mock.Call
}

// SetActive is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - active bool
func (_e *MockRepositoryUser_Expecter) SetActive(ctx interface{}, id interface{}, active interface{}) *MockRepositoryUser_SetActive_Call {
	return &MockRepositoryUser_SetActive_Call{Call: _e.mock.On("SetActive", ctx, id, active)}
}

func (_c *MockRepositoryUser_SetActive_Call) Run(run func(ctx context.Context, id uuid.UUID, active bool)) *MockRepositoryUser_SetActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool))
	})
	return _c
}

func (_c *MockRepositoryUser_SetActive_Call) Return(_a0 entity.User, _a1 error) *MockRepositoryUser_SetActive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryUser_SetActive_Call) RunAndReturn(run func(context.Context, uuid.UUID, bool) (entity.User, error)) *MockRepositoryUser_SetActive_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, name, email
func (_m *MockRepositoryUser) Update(ctx context.Context, id uuid.UUID, name string, email string) (entity.User, error) {
	ret := _m.Called(ctx, id, name, email)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (entity.User, error)); ok {
		return rf(ctx, id, name, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) entity.User); ok {
		r0 = rf(ctx, id, name, email)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, id, name, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryUser_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepositoryUser_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - name string
//   - email string
func (_e *MockRepositoryUser_Expecter) Update(ctx interface{}, id interface{}, name interface{}, email interface{}) *MockRepositoryUser_Update_Call {
	return &MockRepositoryUser_Update_Call{Call: _e.mock.On("Update", ctx, id, name, email)}
}

func (_c *MockRepositoryUser_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, name string, email string)) *MockRepositoryUser_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockRepositoryUser_Update_Call) Return(_a0 entity.User, _a1 error) *MockRepositoryUser_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryUser_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string) (entity.User, error)) *MockRepositoryUser_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryUser creates a new instance of MockRepositoryUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryUser {
	mock := &MockRepositoryUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
