// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"application/app"
	"application/internal/biz"
	"application/internal/datasource"
	"application/internal/service"
	"application/internal/service/handler"
	biz2 "application/internal/user/biz"
	handler2 "application/internal/user/handler"
	"application/internal/user/repo"
	"context"
	"net/http"
)

// Injectors from wire.go:

// wireApp is the composition root for the user service binary. It reuses the
// shared app + HTTP infrastructure and Postgres datasource, adds the shared
// healthz endpoints, and the user + ticket domain stack.
func wireApp(ctx context.Context) (app.Application, error) {
	runTimeFlags := app.NewRunTimeFlags()
	kConfig, err := app.NewKoanfConfig(runTimeFlags)
	if err != nil {
		return nil, err
	}
	appConfig, err := app.NewAppConfig(ctx, kConfig)
	if err != nil {
		return nil, err
	}
	httpServerConfig, err := app.NewHTTPServerConfig(ctx, kConfig)
	if err != nil {
		return nil, err
	}
	appLoggerConfig, err := app.NewAppLoggerConfig(kConfig)
	if err != nil {
		return nil, err
	}
	collectorConfig, err := app.NewCollectorConfig(ctx, kConfig)
	if err != nil {
		return nil, err
	}
	controller := app.NewController()
	otlp, err := app.NewOTLP(ctx, collectorConfig, appConfig, controller, httpServerConfig)
	if err != nil {
		return nil, err
	}
	appLogger, err := app.NewAppLogger(ctx, appConfig, appLoggerConfig, otlp)
	if err != nil {
		return nil, err
	}
	logger := app.NewSlogLogger(appLogger)
	serveMux := http.NewServeMux()
	healthz := biz.NewHealthz(logger, controller)
	healthzHandler := handler.NewMuxHealthzHandler(healthz, logger, serveMux)
	postgresConfig, err := datasource.NewPostgresConfig(ctx, kConfig)
	if err != nil {
		return nil, err
	}
	postgresDB, err := datasource.NewPostgresDB(ctx, logger, controller, postgresConfig)
	if err != nil {
		return nil, err
	}
	user := repo.NewUser(logger, postgresDB)
	bizUser := biz2.NewUser(logger, user)
	handlerUser := handler2.NewUser(logger, serveMux, bizUser)
	ticket := repo.NewTicket(logger, postgresDB)
	bizTicket := biz2.NewTicket(logger, ticket)
	handlerTicket := handler2.NewTicket(logger, serveMux, bizTicket)
	v := handler2.NewServiceList(healthzHandler, handlerUser, handlerTicket)
	httpHandler, err := service.NewHTTPHandler(ctx, logger, serveMux, v...)
	if err != nil {
		return nil, err
	}
	httpServer := app.NewHTTPServer(httpServerConfig, httpHandler, appLogger)
	appApp := app.NewApp(runTimeFlags, appConfig, httpServer, appLogger, controller)
	return appApp, nil
}
