package repo

import (
	"application/internal/datasource"
	"application/internal/media/biz"
	"application/internal/media/entity"
	"context"
	"database/sql"
	"errors"
	"log/slog"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/trace"
)

type media struct {
	logger *slog.Logger
	tracer trace.Tracer
	db     *datasource.PostgresDB
}

var _ biz.Repository = (*media)(nil)

// NewMedia constructs the pgx-backed media repository.
func NewMedia(logger *slog.Logger, db *datasource.PostgresDB) *media {
	return &media{
		logger: logger.With("layer", "MediaRepo"),
		tracer: otel.Tracer("MediaRepo"),
		db:     db,
	}
}

const selectColumns = `id, owner_type, owner_id, kind, bucket, object_key,
	content_type, size_bytes, width, height, duration_seconds, position, created_at`

// Create inserts a media row (id is pre-generated by the use case) and returns
// the stored record with its DB-assigned created_at.
func (r *media) Create(ctx context.Context, m entity.Media) (entity.Media, error) {
	logger := r.logger.With("method", "Create")

	var duration sql.NullFloat64
	if m.DurationSeconds != nil {
		duration = sql.NullFloat64{Float64: *m.DurationSeconds, Valid: true}
	}

	query := `INSERT INTO media (id, owner_type, owner_id, kind, bucket, object_key,
		content_type, size_bytes, width, height, duration_seconds, position)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
		RETURNING created_at`

	row := r.db.QueryRowContext(ctx, query,
		m.ID, m.OwnerType, m.OwnerID, string(m.Kind), m.Bucket, m.ObjectKey,
		m.ContentType, m.SizeBytes, m.Width, m.Height, duration, m.Position,
	)

	if err := row.Scan(&m.CreatedAt); err != nil {
		logger.WarnContext(ctx, "failed to insert media", "error", err)

		return entity.Media{}, err
	}

	return m, nil
}

// Get returns a media row by id, mapping a missing row to ErrResourceNotFound.
func (r *media) Get(ctx context.Context, id uuid.UUID) (entity.Media, error) {
	logger := r.logger.With("method", "Get")

	query := `SELECT ` + selectColumns + ` FROM media WHERE id = $1`
	row := r.db.QueryRowContext(ctx, query, id)

	m, err := scanMedia(row)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return entity.Media{}, biz.ErrResourceNotFound
		}

		logger.WarnContext(ctx, "failed to scan media", "error", err)

		return entity.Media{}, err
	}

	return m, nil
}

// ListByOwner returns every media row for an owner, ordered by position.
func (r *media) ListByOwner(
	ctx context.Context,
	ownerType string,
	ownerID uuid.UUID,
) ([]entity.Media, error) {
	logger := r.logger.With("method", "ListByOwner")

	query := `SELECT ` + selectColumns + ` FROM media
		WHERE owner_type = $1 AND owner_id = $2
		ORDER BY position ASC, created_at ASC`

	rows, err := r.db.QueryContext(ctx, query, ownerType, ownerID)
	if err != nil {
		logger.WarnContext(ctx, "failed to query media", "error", err)

		return nil, err
	}
	defer rows.Close()

	var out []entity.Media

	for rows.Next() {
		m, err := scanMedia(rows)
		if err != nil {
			logger.WarnContext(ctx, "failed to scan media row", "error", err)

			continue
		}

		out = append(out, m)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return out, nil
}

// scanner abstracts *sql.Row and *sql.Rows for a shared scan routine.
type scanner interface {
	Scan(dest ...any) error
}

func scanMedia(s scanner) (entity.Media, error) {
	var (
		m        entity.Media
		kind     string
		duration sql.NullFloat64
	)

	if err := s.Scan(
		&m.ID, &m.OwnerType, &m.OwnerID, &kind, &m.Bucket, &m.ObjectKey,
		&m.ContentType, &m.SizeBytes, &m.Width, &m.Height, &duration, &m.Position, &m.CreatedAt,
	); err != nil {
		return entity.Media{}, err
	}

	m.Kind = entity.Kind(kind)

	if duration.Valid {
		d := duration.Float64
		m.DurationSeconds = &d
	}

	return m, nil
}
