// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"application/app"
	"application/internal/biz"
	"application/internal/datasource"
	biz2 "application/internal/media/biz"
	handler2 "application/internal/media/handler"
	"application/internal/media/repo"
	"application/internal/service"
	"application/internal/service/handler"
	"context"
	"net/http"
)

// Injectors from wire.go:

// wireApp is the composition root for the media service binary. It reuses the
// shared app + HTTP infrastructure, adds Postgres + MinIO datasources, the
// shared healthz endpoints, and the media domain stack.
func wireApp(ctx context.Context) (app.Application, error) {
	runTimeFlags := app.NewRunTimeFlags()
	kConfig, err := app.NewKoanfConfig(runTimeFlags)
	if err != nil {
		return nil, err
	}
	appConfig, err := app.NewAppConfig(ctx, kConfig)
	if err != nil {
		return nil, err
	}
	httpServerConfig, err := app.NewHTTPServerConfig(ctx, kConfig)
	if err != nil {
		return nil, err
	}
	appLoggerConfig, err := app.NewAppLoggerConfig(kConfig)
	if err != nil {
		return nil, err
	}
	collectorConfig, err := app.NewCollectorConfig(ctx, kConfig)
	if err != nil {
		return nil, err
	}
	controller := app.NewController()
	otlp, err := app.NewOTLP(ctx, collectorConfig, appConfig, controller, httpServerConfig)
	if err != nil {
		return nil, err
	}
	appLogger, err := app.NewAppLogger(ctx, appConfig, appLoggerConfig, otlp)
	if err != nil {
		return nil, err
	}
	logger := app.NewSlogLogger(appLogger)
	serveMux := http.NewServeMux()
	healthz := biz.NewHealthz(logger, controller)
	healthzHandler := handler.NewMuxHealthzHandler(healthz, logger, serveMux)
	postgresConfig, err := datasource.NewPostgresConfig(ctx, kConfig)
	if err != nil {
		return nil, err
	}
	postgresDB, err := datasource.NewPostgresDB(ctx, logger, controller, postgresConfig)
	if err != nil {
		return nil, err
	}
	media := repo.NewMedia(logger, postgresDB)
	minioConfig, err := datasource.NewMinioConfig(ctx, kConfig)
	if err != nil {
		return nil, err
	}
	minioStorage, err := datasource.NewMinioStorage(ctx, logger, controller, minioConfig)
	if err != nil {
		return nil, err
	}
	bizMedia := biz2.NewMedia(logger, media, minioStorage)
	handlerMedia := handler2.NewMedia(logger, serveMux, bizMedia)
	v := handler2.NewServiceList(healthzHandler, handlerMedia)
	httpHandler, err := service.NewHTTPHandler(ctx, logger, serveMux, v...)
	if err != nil {
		return nil, err
	}
	httpServer := app.NewHTTPServer(httpServerConfig, httpHandler, appLogger)
	appApp := app.NewApp(runTimeFlags, appConfig, httpServer, appLogger, controller)
	return appApp, nil
}
