// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	biz "application/internal/adminauth/biz"
	context "context"

	entity "application/internal/adminauth/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUsecaseAccounts is an autogenerated mock type for the UsecaseAccounts type
type MockUsecaseAccounts struct {
	mock.Mock
}

type MockUsecaseAccounts_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecaseAccounts) EXPECT() *MockUsecaseAccounts_Expecter {
	return &MockUsecaseAccounts_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, input
func (_m *MockUsecaseAccounts) Create(ctx context.Context, input biz.CreateAccountInput) (entity.AdminAccount, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.AdminAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.CreateAccountInput) (entity.AdminAccount, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, biz.CreateAccountInput) entity.AdminAccount); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(entity.AdminAccount)
	}

	if rf, ok := ret.Get(1).(func(context.Context, biz.CreateAccountInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseAccounts_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUsecaseAccounts_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input biz.CreateAccountInput
func (_e *MockUsecaseAccounts_Expecter) Create(ctx interface{}, input interface{}) *MockUsecaseAccounts_Create_Call {
	return &MockUsecaseAccounts_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *MockUsecaseAccounts_Create_Call) Run(run func(ctx context.Context, input biz.CreateAccountInput)) *MockUsecaseAccounts_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.CreateAccountInput))
	})
	return _c
}

func (_c *MockUsecaseAccounts_Create_Call) Return(_a0 entity.AdminAccount, _a1 error) *MockUsecaseAccounts_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseAccounts_Create_Call) RunAndReturn(run func(context.Context, biz.CreateAccountInput) (entity.AdminAccount, error)) *MockUsecaseAccounts_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockUsecaseAccounts) List(ctx context.Context) ([]entity.AdminAccount, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.AdminAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.AdminAccount, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.AdminAccount); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.AdminAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseAccounts_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUsecaseAccounts_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUsecaseAccounts_Expecter) List(ctx interface{}) *MockUsecaseAccounts_List_Call {
	return &MockUsecaseAccounts_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockUsecaseAccounts_List_Call) Run(run func(ctx context.Context)) *MockUsecaseAccounts_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUsecaseAccounts_List_Call) Return(_a0 []entity.AdminAccount, _a1 error) *MockUsecaseAccounts_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseAccounts_List_Call) RunAndReturn(run func(context.Context) ([]entity.AdminAccount, error)) *MockUsecaseAccounts_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, input
func (_m *MockUsecaseAccounts) Update(ctx context.Context, id uuid.UUID, input biz.UpdateAccountInput) (entity.AdminAccount, error) {
	ret := _m.Called(ctx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 entity.AdminAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, biz.UpdateAccountInput) (entity.AdminAccount, error)); ok {
		return rf(ctx, id, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, biz.UpdateAccountInput) entity.AdminAccount); ok {
		r0 = rf(ctx, id, input)
	} else {
		r0 = ret.Get(0).(entity.AdminAccount)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, biz.UpdateAccountInput) error); ok {
		r1 = rf(ctx, id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseAccounts_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUsecaseAccounts_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - input biz.UpdateAccountInput
func (_e *MockUsecaseAccounts_Expecter) Update(ctx interface{}, id interface{}, input interface{}) *MockUsecaseAccounts_Update_Call {
	return &MockUsecaseAccounts_Update_Call{Call: _e.mock.On("Update", ctx, id, input)}
}

func (_c *MockUsecaseAccounts_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, input biz.UpdateAccountInput)) *MockUsecaseAccounts_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(biz.UpdateAccountInput))
	})
	return _c
}

func (_c *MockUsecaseAccounts_Update_Call) Return(_a0 entity.AdminAccount, _a1 error) *MockUsecaseAccounts_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseAccounts_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, biz.UpdateAccountInput) (entity.AdminAccount, error)) *MockUsecaseAccounts_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecaseAccounts creates a new instance of MockUsecaseAccounts. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecaseAccounts(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecaseAccounts {
	mock := &MockUsecaseAccounts{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
