// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	biz "application/internal/adminauth/biz"
	context "context"

	entity "application/internal/adminauth/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockUsecaseAuth is an autogenerated mock type for the UsecaseAuth type
type MockUsecaseAuth struct {
	mock.Mock
}

type MockUsecaseAuth_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecaseAuth) EXPECT() *MockUsecaseAuth_Expecter {
	return &MockUsecaseAuth_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, email, password, clientIP
func (_m *MockUsecaseAuth) Login(ctx context.Context, email string, password string, clientIP string) (biz.LoginResult, error) {
	ret := _m.Called(ctx, email, password, clientIP)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 biz.LoginResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (biz.LoginResult, error)); ok {
		return rf(ctx, email, password, clientIP)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) biz.LoginResult); ok {
		r0 = rf(ctx, email, password, clientIP)
	} else {
		r0 = ret.Get(0).(biz.LoginResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, email, password, clientIP)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseAuth_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockUsecaseAuth_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
//   - clientIP string
func (_e *MockUsecaseAuth_Expecter) Login(ctx interface{}, email interface{}, password interface{}, clientIP interface{}) *MockUsecaseAuth_Login_Call {
	return &MockUsecaseAuth_Login_Call{Call: _e.mock.On("Login", ctx, email, password, clientIP)}
}

func (_c *MockUsecaseAuth_Login_Call) Run(run func(ctx context.Context, email string, password string, clientIP string)) *MockUsecaseAuth_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockUsecaseAuth_Login_Call) Return(_a0 biz.LoginResult, _a1 error) *MockUsecaseAuth_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseAuth_Login_Call) RunAndReturn(run func(context.Context, string, string, string) (biz.LoginResult, error)) *MockUsecaseAuth_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, refreshToken
func (_m *MockUsecaseAuth) Logout(ctx context.Context, refreshToken string) error {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsecaseAuth_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockUsecaseAuth_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockUsecaseAuth_Expecter) Logout(ctx interface{}, refreshToken interface{}) *MockUsecaseAuth_Logout_Call {
	return &MockUsecaseAuth_Logout_Call{Call: _e.mock.On("Logout", ctx, refreshToken)}
}

func (_c *MockUsecaseAuth_Logout_Call) Run(run func(ctx context.Context, refreshToken string)) *MockUsecaseAuth_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUsecaseAuth_Logout_Call) Return(_a0 error) *MockUsecaseAuth_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsecaseAuth_Logout_Call) RunAndReturn(run func(context.Context, string) error) *MockUsecaseAuth_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Me provides a mock function with given fields: ctx, adminID
func (_m *MockUsecaseAuth) Me(ctx context.Context, adminID string) (entity.AdminAccount, error) {
	ret := _m.Called(ctx, adminID)

	if len(ret) == 0 {
		panic("no return value specified for Me")
	}

	var r0 entity.AdminAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entity.AdminAccount, error)); ok {
		return rf(ctx, adminID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entity.AdminAccount); ok {
		r0 = rf(ctx, adminID)
	} else {
		r0 = ret.Get(0).(entity.AdminAccount)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, adminID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseAuth_Me_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Me'
type MockUsecaseAuth_Me_Call struct {
	*mock.Call
}

// Me is a helper method to define mock.On call
//   - ctx context.Context
//   - adminID string
func (_e *MockUsecaseAuth_Expecter) Me(ctx interface{}, adminID interface{}) *MockUsecaseAuth_Me_Call {
	return &MockUsecaseAuth_Me_Call{Call: _e.mock.On("Me", ctx, adminID)}
}

func (_c *MockUsecaseAuth_Me_Call) Run(run func(ctx context.Context, adminID string)) *MockUsecaseAuth_Me_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUsecaseAuth_Me_Call) Return(_a0 entity.AdminAccount, _a1 error) *MockUsecaseAuth_Me_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseAuth_Me_Call) RunAndReturn(run func(context.Context, string) (entity.AdminAccount, error)) *MockUsecaseAuth_Me_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function with given fields: ctx, refreshToken
func (_m *MockUsecaseAuth) Refresh(ctx context.Context, refreshToken string) (biz.LoginResult, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 biz.LoginResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (biz.LoginResult, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) biz.LoginResult); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Get(0).(biz.LoginResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseAuth_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockUsecaseAuth_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockUsecaseAuth_Expecter) Refresh(ctx interface{}, refreshToken interface{}) *MockUsecaseAuth_Refresh_Call {
	return &MockUsecaseAuth_Refresh_Call{Call: _e.mock.On("Refresh", ctx, refreshToken)}
}

func (_c *MockUsecaseAuth_Refresh_Call) Run(run func(ctx context.Context, refreshToken string)) *MockUsecaseAuth_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUsecaseAuth_Refresh_Call) Return(_a0 biz.LoginResult, _a1 error) *MockUsecaseAuth_Refresh_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseAuth_Refresh_Call) RunAndReturn(run func(context.Context, string) (biz.LoginResult, error)) *MockUsecaseAuth_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecaseAuth creates a new instance of MockUsecaseAuth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecaseAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecaseAuth {
	mock := &MockUsecaseAuth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
