// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "application/internal/adminauth/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CountActiveSuperadmins provides a mock function with given fields: ctx
func (_m *MockRepository) CountActiveSuperadmins(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountActiveSuperadmins")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CountActiveSuperadmins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountActiveSuperadmins'
type MockRepository_CountActiveSuperadmins_Call struct {
	*mock.Call
}

// CountActiveSuperadmins is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) CountActiveSuperadmins(ctx interface{}) *MockRepository_CountActiveSuperadmins_Call {
	return &MockRepository_CountActiveSuperadmins_Call{Call: _e.mock.On("CountActiveSuperadmins", ctx)}
}

func (_c *MockRepository_CountActiveSuperadmins_Call) Run(run func(ctx context.Context)) *MockRepository_CountActiveSuperadmins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_CountActiveSuperadmins_Call) Return(_a0 int, _a1 error) *MockRepository_CountActiveSuperadmins_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CountActiveSuperadmins_Call) RunAndReturn(run func(context.Context) (int, error)) *MockRepository_CountActiveSuperadmins_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAccount provides a mock function with given fields: ctx, a
func (_m *MockRepository) CreateAccount(ctx context.Context, a entity.AdminAccount) (entity.AdminAccount, error) {
	ret := _m.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 entity.AdminAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.AdminAccount) (entity.AdminAccount, error)); ok {
		return rf(ctx, a)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.AdminAccount) entity.AdminAccount); ok {
		r0 = rf(ctx, a)
	} else {
		r0 = ret.Get(0).(entity.AdminAccount)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.AdminAccount) error); ok {
		r1 = rf(ctx, a)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type MockRepository_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - a entity.AdminAccount
func (_e *MockRepository_Expecter) CreateAccount(ctx interface{}, a interface{}) *MockRepository_CreateAccount_Call {
	return &MockRepository_CreateAccount_Call{Call: _e.mock.On("CreateAccount", ctx, a)}
}

func (_c *MockRepository_CreateAccount_Call) Run(run func(ctx context.Context, a entity.AdminAccount)) *MockRepository_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.AdminAccount))
	})
	return _c
}

func (_c *MockRepository_CreateAccount_Call) Return(_a0 entity.AdminAccount, _a1 error) *MockRepository_CreateAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateAccount_Call) RunAndReturn(run func(context.Context, entity.AdminAccount) (entity.AdminAccount, error)) *MockRepository_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRefreshToken provides a mock function with given fields: ctx, t
func (_m *MockRepository) CreateRefreshToken(ctx context.Context, t entity.RefreshToken) error {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for CreateRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.RefreshToken) error); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRefreshToken'
type MockRepository_CreateRefreshToken_Call struct {
	*mock.Call
}

// CreateRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - t entity.RefreshToken
func (_e *MockRepository_Expecter) CreateRefreshToken(ctx interface{}, t interface{}) *MockRepository_CreateRefreshToken_Call {
	return &MockRepository_CreateRefreshToken_Call{Call: _e.mock.On("CreateRefreshToken", ctx, t)}
}

func (_c *MockRepository_CreateRefreshToken_Call) Run(run func(ctx context.Context, t entity.RefreshToken)) *MockRepository_CreateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.RefreshToken))
	})
	return _c
}

func (_c *MockRepository_CreateRefreshToken_Call) Return(_a0 error) *MockRepository_CreateRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateRefreshToken_Call) RunAndReturn(run func(context.Context, entity.RefreshToken) error) *MockRepository_CreateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccount provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetAccount(ctx context.Context, id uuid.UUID) (entity.AdminAccount, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 entity.AdminAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.AdminAccount, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.AdminAccount); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.AdminAccount)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type MockRepository_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) GetAccount(ctx interface{}, id interface{}) *MockRepository_GetAccount_Call {
	return &MockRepository_GetAccount_Call{Call: _e.mock.On("GetAccount", ctx, id)}
}

func (_c *MockRepository_GetAccount_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_GetAccount_Call) Return(_a0 entity.AdminAccount, _a1 error) *MockRepository_GetAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetAccount_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.AdminAccount, error)) *MockRepository_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountByEmail provides a mock function with given fields: ctx, email
func (_m *MockRepository) GetAccountByEmail(ctx context.Context, email string) (entity.AdminAccount, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountByEmail")
	}

	var r0 entity.AdminAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entity.AdminAccount, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entity.AdminAccount); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(entity.AdminAccount)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetAccountByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountByEmail'
type MockRepository_GetAccountByEmail_Call struct {
	*mock.Call
}

// GetAccountByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockRepository_Expecter) GetAccountByEmail(ctx interface{}, email interface{}) *MockRepository_GetAccountByEmail_Call {
	return &MockRepository_GetAccountByEmail_Call{Call: _e.mock.On("GetAccountByEmail", ctx, email)}
}

func (_c *MockRepository_GetAccountByEmail_Call) Run(run func(ctx context.Context, email string)) *MockRepository_GetAccountByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetAccountByEmail_Call) Return(_a0 entity.AdminAccount, _a1 error) *MockRepository_GetAccountByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetAccountByEmail_Call) RunAndReturn(run func(context.Context, string) (entity.AdminAccount, error)) *MockRepository_GetAccountByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshToken provides a mock function with given fields: ctx, tokenHash
func (_m *MockRepository) GetRefreshToken(ctx context.Context, tokenHash string) (entity.RefreshToken, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshToken")
	}

	var r0 entity.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entity.RefreshToken, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entity.RefreshToken); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Get(0).(entity.RefreshToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshToken'
type MockRepository_GetRefreshToken_Call struct {
	*mock.Call
}

// GetRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockRepository_Expecter) GetRefreshToken(ctx interface{}, tokenHash interface{}) *MockRepository_GetRefreshToken_Call {
	return &MockRepository_GetRefreshToken_Call{Call: _e.mock.On("GetRefreshToken", ctx, tokenHash)}
}

func (_c *MockRepository_GetRefreshToken_Call) Run(run func(ctx context.Context, tokenHash string)) *MockRepository_GetRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetRefreshToken_Call) Return(_a0 entity.RefreshToken, _a1 error) *MockRepository_GetRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetRefreshToken_Call) RunAndReturn(run func(context.Context, string) (entity.RefreshToken, error)) *MockRepository_GetRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// ListAccounts provides a mock function with given fields: ctx
func (_m *MockRepository) ListAccounts(ctx context.Context) ([]entity.AdminAccount, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAccounts")
	}

	var r0 []entity.AdminAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.AdminAccount, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.AdminAccount); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.AdminAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAccounts'
type MockRepository_ListAccounts_Call struct {
	*mock.Call
}

// ListAccounts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListAccounts(ctx interface{}) *MockRepository_ListAccounts_Call {
	return &MockRepository_ListAccounts_Call{Call: _e.mock.On("ListAccounts", ctx)}
}

func (_c *MockRepository_ListAccounts_Call) Run(run func(ctx context.Context)) *MockRepository_ListAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_ListAccounts_Call) Return(_a0 []entity.AdminAccount, _a1 error) *MockRepository_ListAccounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListAccounts_Call) RunAndReturn(run func(context.Context) ([]entity.AdminAccount, error)) *MockRepository_ListAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRefreshRotated provides a mock function with given fields: ctx, id, at
func (_m *MockRepository) MarkRefreshRotated(ctx context.Context, id uuid.UUID, at time.Time) error {
	ret := _m.Called(ctx, id, at)

	if len(ret) == 0 {
		panic("no return value specified for MarkRefreshRotated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, id, at)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_MarkRefreshRotated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRefreshRotated'
type MockRepository_MarkRefreshRotated_Call struct {
	*mock.Call
}

// MarkRefreshRotated is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - at time.Time
func (_e *MockRepository_Expecter) MarkRefreshRotated(ctx interface{}, id interface{}, at interface{}) *MockRepository_MarkRefreshRotated_Call {
	return &MockRepository_MarkRefreshRotated_Call{Call: _e.mock.On("MarkRefreshRotated", ctx, id, at)}
}

func (_c *MockRepository_MarkRefreshRotated_Call) Run(run func(ctx context.Context, id uuid.UUID, at time.Time)) *MockRepository_MarkRefreshRotated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockRepository_MarkRefreshRotated_Call) Return(_a0 error) *MockRepository_MarkRefreshRotated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_MarkRefreshRotated_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) error) *MockRepository_MarkRefreshRotated_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllForAdmin provides a mock function with given fields: ctx, adminID, at
func (_m *MockRepository) RevokeAllForAdmin(ctx context.Context, adminID uuid.UUID, at time.Time) error {
	ret := _m.Called(ctx, adminID, at)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllForAdmin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, adminID, at)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_RevokeAllForAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllForAdmin'
type MockRepository_RevokeAllForAdmin_Call struct {
	*mock.Call
}

// RevokeAllForAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - adminID uuid.UUID
//   - at time.Time
func (_e *MockRepository_Expecter) RevokeAllForAdmin(ctx interface{}, adminID interface{}, at interface{}) *MockRepository_RevokeAllForAdmin_Call {
	return &MockRepository_RevokeAllForAdmin_Call{Call: _e.mock.On("RevokeAllForAdmin", ctx, adminID, at)}
}

func (_c *MockRepository_RevokeAllForAdmin_Call) Run(run func(ctx context.Context, adminID uuid.UUID, at time.Time)) *MockRepository_RevokeAllForAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockRepository_RevokeAllForAdmin_Call) Return(_a0 error) *MockRepository_RevokeAllForAdmin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_RevokeAllForAdmin_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) error) *MockRepository_RevokeAllForAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeRefreshToken provides a mock function with given fields: ctx, tokenHash, at
func (_m *MockRepository) RevokeRefreshToken(ctx context.Context, tokenHash string, at time.Time) error {
	ret := _m.Called(ctx, tokenHash, at)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, tokenHash, at)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_RevokeRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeRefreshToken'
type MockRepository_RevokeRefreshToken_Call struct {
	*mock.Call
}

// RevokeRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
//   - at time.Time
func (_e *MockRepository_Expecter) RevokeRefreshToken(ctx interface{}, tokenHash interface{}, at interface{}) *MockRepository_RevokeRefreshToken_Call {
	return &MockRepository_RevokeRefreshToken_Call{Call: _e.mock.On("RevokeRefreshToken", ctx, tokenHash, at)}
}

func (_c *MockRepository_RevokeRefreshToken_Call) Run(run func(ctx context.Context, tokenHash string, at time.Time)) *MockRepository_RevokeRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *MockRepository_RevokeRefreshToken_Call) Return(_a0 error) *MockRepository_RevokeRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_RevokeRefreshToken_Call) RunAndReturn(run func(context.Context, string, time.Time) error) *MockRepository_RevokeRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// TouchLastLogin provides a mock function with given fields: ctx, id, at
func (_m *MockRepository) TouchLastLogin(ctx context.Context, id uuid.UUID, at time.Time) error {
	ret := _m.Called(ctx, id, at)

	if len(ret) == 0 {
		panic("no return value specified for TouchLastLogin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, id, at)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_TouchLastLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TouchLastLogin'
type MockRepository_TouchLastLogin_Call struct {
	*mock.Call
}

// TouchLastLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - at time.Time
func (_e *MockRepository_Expecter) TouchLastLogin(ctx interface{}, id interface{}, at interface{}) *MockRepository_TouchLastLogin_Call {
	return &MockRepository_TouchLastLogin_Call{Call: _e.mock.On("TouchLastLogin", ctx, id, at)}
}

func (_c *MockRepository_TouchLastLogin_Call) Run(run func(ctx context.Context, id uuid.UUID, at time.Time)) *MockRepository_TouchLastLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockRepository_TouchLastLogin_Call) Return(_a0 error) *MockRepository_TouchLastLogin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_TouchLastLogin_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) error) *MockRepository_TouchLastLogin_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAccount provides a mock function with given fields: ctx, a
func (_m *MockRepository) UpdateAccount(ctx context.Context, a entity.AdminAccount) (entity.AdminAccount, error) {
	ret := _m.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccount")
	}

	var r0 entity.AdminAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.AdminAccount) (entity.AdminAccount, error)); ok {
		return rf(ctx, a)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.AdminAccount) entity.AdminAccount); ok {
		r0 = rf(ctx, a)
	} else {
		r0 = ret.Get(0).(entity.AdminAccount)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.AdminAccount) error); ok {
		r1 = rf(ctx, a)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpdateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAccount'
type MockRepository_UpdateAccount_Call struct {
	*mock.Call
}

// UpdateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - a entity.AdminAccount
func (_e *MockRepository_Expecter) UpdateAccount(ctx interface{}, a interface{}) *MockRepository_UpdateAccount_Call {
	return &MockRepository_UpdateAccount_Call{Call: _e.mock.On("UpdateAccount", ctx, a)}
}

func (_c *MockRepository_UpdateAccount_Call) Run(run func(ctx context.Context, a entity.AdminAccount)) *MockRepository_UpdateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.AdminAccount))
	})
	return _c
}

func (_c *MockRepository_UpdateAccount_Call) Return(_a0 entity.AdminAccount, _a1 error) *MockRepository_UpdateAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpdateAccount_Call) RunAndReturn(run func(context.Context, entity.AdminAccount) (entity.AdminAccount, error)) *MockRepository_UpdateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
